services:

  service2:
    build: ./service2
    networks:
      - devops_network


  service1:
    build: ./service1
    networks:
      - devops_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 4

  front_end:
    build: ./front_end
    ports:
      - 8198:8197
    networks:
      - devops_network


  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - devops_network
    ports:
      - 8198:8198
    depends_on:
      - service2
      - service1


networks:
  devops_network:
    driver: bridge